#token = "your_telegram_bot_token"
db = "data/db.sqlite"
game_exp = "72h"

[default_cfg]
locale  = "en"
lang_id = "en"
#pack_id = "A1"

[[translations]]
locale = "en"
name   = "English"
path   = "i18n/active.en.toml"

[[translations]]
locale = "ru"
name   = "Русский"
path   = "i18n/active.ru.toml"

[[languages]]
id   = "en"
name = "English"

#[[languages.word_packs]]
#id   = "A1"
#name = "A1"
#path = "data/en/A1.txt"
